### ISSUE TITLE
[webgl2] Add Error Handling

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#71] opened 2018-06-25 02:46 UTC
There is no error handling. For example, passing an invalid parameter should throw an error.

**_Invalid scenes:_**
**addOperand()**:

- TENSOR_FLOAT32 type: no "dimensions"
- TENSOR_INT32 type: no "dimensions"
- TENSOR_QUANT8_ASYMM type: no "dimensions"
- TENSOR_QUANT8_ASYMM type: no "scale"
- addOperand() only requires one argument, passing two arguments should raise an error: two scalars or two tensors

**setOperandValue():**

- Add an operand with a TENSOR_QUANT8_ASYMM tensor, but set its value to a different type: set Int8Array data

**addOperation():**

- One of the inputs is not the required type(TENSOR_FLOAT32 or TENSOR_QUANT8_ASYMM)
- The input or output tensor rank is not matched with the required
- The type of the second tensor is not same with the first one for ‘ADD’ operation
- The length of inputs are not 7 or 10 for "AVERAGE_POOL_2D" operation
- The input tensors don't have identical type or the same dimensions for "CONCATENATION" operation
- ...

**identifyInputsAndOutputs():**

- The output is equal to the input
- Pass more than two parameter

**finish()**: pass a parameter
**createCompilation()**: call this function when the model is not being finished
...

**Comment by ganwenyao** [comment] 2018-06-26 07:39
Duplicate of #72, closed it.

**Closed by ganwenyao** 2018-06-26 07:39 UTC
