### ISSUE TITLE
[MPS] Chromium crashed and then reloaded when running cts tests with MPS backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#171] opened 2018-08-28 06:50 UTC
**Test Env:**
Chromium Version : nightly build 70.0.3503.0 (**public/webml/nightly/007f215/**)
OS : Mac OS
webml-polyfill: commit 777b85f

**Expected Result:**
No crash.

**Actual Result:**
Chromium crashed and then reloaded when running cts tests.

**How to Reproduce:**
1. Launch chromium and enable the WebML
2. Run the tests: https://brucedai.github.io/nt/testm/cts-all.html?backend=mps

_Similar issue for BNNS: #147 _

Crash log:

```
[11032:775:0816/151540.443062:ERROR:execution_impl_mac.mm(93)] number of images 5 is not supported
/BuildRoot/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MetalPerformanceShaders-100.6/MPSCore/Types/MPSImage.mm:611: failed assertion `[MPSImage initWithDevice:imageDescriptor:] descriptor may not be nil.'
Received signal 6
 [0x0001100c16ec]
 [0x0001100c15e1]
 [0x7fff5f08df5a]
 [0x000000000060]
 [0x7fff5ee2b1ae]
 [0x7fff5edf31ac]
 [0x7fff3b1c885d]
 [0x7fff3b21f0d5]
 [0x00010ee0370f]
 [0x00010ee01b1b]
 [0x00010ee0ab0f]
 [0x00010ee07c56]
 [0x0001106aaa98]
 [0x0001106af141]
 [0x0001106ae974]
 [0x0001106a8ba1]
 [0x0001106a9251]
 [0x0001105e94b8]
 [0x000110010f32]
 [0x000110031adf]
 [0x000110031fa8]
 [0x00011003416a]
 [0x0001100241ea]
 [0x000110033a8f]
 [0x7fff36a83a61]
 [0x7fff36b3d47c]
 [0x7fff36a664c0]
 [0x7fff36a6593d]
 [0x7fff36a651a3]
 [0x7fff38b54f26]
 [0x0001100347cd]
 [0x0001100335ae]
 [0x000110056555]
 [0x00011413334c]
 [0x00010fc08729]
 [0x00011147ba01]
 [0x00010fc078f4]
 [0x00010dcf9a03]
 [0x0001085bf131]
 [0x7fff5ed7f015]
[end of stack trace]
[11040:775:0816/151540.952402:ERROR:gles2_cmd_decoder.cc(18059)] [.BrowserCompositor-0x7f883a840200]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[11040:775:0816/151540.952486:ERROR:gles2_cmd_decoder.cc(12532)] [.BrowserCompositor-0x7f883a840200]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[11040:775:0816/151540.952512:ERROR:gles2_cmd_decoder.cc(18059)] [.BrowserCompositor-0x7f883a840200]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[11040:775:0816/151540.952535:ERROR:gles2_cmd_decoder.cc(12532)] [.BrowserCompositor-0x7f883a840200]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
```

**Comment by sunlin-link** [comment] 2018-09-21 05:55
@Christywl Fixed. Please verify

**Comment by Christywl** [comment] 2018-09-25 05:57
@sunlin-link , I tried the chromium nightly build **_313c1c2_**, this issue was still reproduced sometimes(not 100%). Run the tests: https://brucedai.github.io/nt/testm/cts-all.html?backend=mps
```
$ ./313c1c2/mac_x64_SUCCEED/Chromium.app/Ctents/MacOS/Chromium 
[855:775:0925/134530.869409:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134530.869822:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134530.869867:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134530.869987:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134530.870025:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[865:775:0925/134532.119663:ERROR:webthread_impl_for_utility_thread.cc(19)] Not implemented reached in virtual blink::ThreadScheduler *blink::scheduler::WebThreadImplForUtilityThread::Scheduler() const
[855:775:0925/134533.874061:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.874458:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.874501:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.874558:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.874593:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.897854:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.898362:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.898416:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.898491:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.898575:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.915315:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.916587:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.916724:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.917205:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.917395:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.931369:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.932286:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.932422:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.932752:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.932883:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.948663:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.950105:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.950266:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.950615:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.950918:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.966612:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.968283:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.968469:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.968827:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.968960:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.982222:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.983080:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.983235:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.983429:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[855:775:0925/134533.983574:ERROR:native_view_host_mac.mm(177)] Not implemented reached in virtual void views::NativeViewHostMac::ShowWidget(int, int, int, int, int, int)
[860:775:0925/134534.568479:ERROR:execution_impl_mac.mm(93)] number of images 5 is not supported
Received signal 11 <unknown> 000000000000
 [0x00010e52f5ec]
 [0x00010e52f4e1]
 [0x7fff71065f5a]
 [0x000000000000]
 [0x00010d271c3e]
 [0x00010d27064c]
 [0x00010eb196ac]
 [0x00010eb1d556]
 [0x00010eb1ba02]
 [0x00010eb1a7ed]
 [0x00010eb1686b]
 [0x00010ea573b8]
 [0x00010e47ee32]
 [0x00010e49f9df]
 [0x00010e49fea8]
 [0x00010e4a206a]
 [0x00010e4920ea]
 [0x00010e4a198f]
 [0x7fff48f34a11]
 [0x7fff48fee42c]
 [0x7fff48f17470]
 [0x7fff48f168ed]
 [0x7fff48f16153]
 [0x7fff4b012f26]
 [0x00010e4a26cd]
 [0x00010e4a14ae]
 [0x00010e4c4455]
 [0x0001125a144c]
 [0x00010e076629]
 [0x00010f8e9901]
 [0x00010e0757f4]
 [0x00010c167403]
 [0x000107332131]
 [0x7fff70d57015]
[end of stack trace]
[868:775:0925/134535.623745:ERROR:gles2_cmd_decoder.cc(18059)] [.BrowserCompositor-0x7fb04891fa00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[868:775:0925/134535.623892:ERROR:gles2_cmd_decoder.cc(12532)] [.BrowserCompositor-0x7fb04891fa00]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[868:775:0925/134535.623926:ERROR:gles2_cmd_decoder.cc(18059)] [.BrowserCompositor-0x7fb04891fa00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[868:775:0925/134535.623954:ERROR:gles2_cmd_decoder.cc(12532)] [.BrowserCompositor-0x7fb04891fa00]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[868:775:0925/134535.623978:ERROR:gles2_cmd_decoder.cc(18059)] [.BrowserCompositor-0x7fb04891fa00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
[868:775:0925/134535.624012:ERROR:gles2_cmd_decoder.cc(12532)] [.BrowserCompositor-0x7fb04891fa00]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
```

**Comment by fujunwei** [comment] 2018-10-26 08:02
The root cause of it is `ExecutionImplMac`  reference `CompilationImplMac` with raw pointer in https://github.com/otcshare/chromium-src/blob/webml/services/ml/execution_impl_mac.mm#L132 that need [base::weak_ptr](https://cs.chromium.org/chromium/src/base/memory/weak_ptr.h?l=223&gsn=WeakPtr
), @lisa0314  is refactoring.

**Comment by lisa0314** [comment] 2018-11-13 05:17
This issue has been fixed by [#PR49](https://github.com/otcshare/chromium-src/pull/49). @Christywl Please help to verify.

**Closed by lisa0314** 2018-11-13 05:17 UTC
Labels: bug, p1
