### ISSUE TITLE
Chromium crashed when testing reshape using special value -1 on MacOS(MPS) device

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#61] opened 2018-06-06 08:12 UTC
### Test Env
Chromium Version :  nightly build 65.0.3324.0 (revision f9e1a31)
Operating System : MacOS

### Expected behavior

Test should be PASS.

### Actual behavior
Crash occurs.

### How to reproduce  
1. Download and install Chromium
2. Launch  Chromium
3. Run test case on Chromium: 
https://brucedai.github.io/nt/test/reshape_neg1.html for reshape test using special value -1.

### Analyze
The set dimensions as [2, -1] of Line 14 in https://github.com/intel/webml-polyfill/blob/master/test/operations/reshape_neg1.js
```javascript
model.addOperand({type: nn.TENSOR_FLOAT32, dimensions: [2, -1]});
```
can not have the same effect as the reshape function of numpy in python version does.
```python
    #numpy reshape with -1 example
    import numpy as np
    a = np.array([[1,2,3], [4,5,6]])
    np.reshape(a, (3,-1))       # the unspecified value is inferred to be 2
    >>>array([[1, 2],
           [3, 4],
           [5, 6]])
```

**Comment by sunlin-link** [comment] 2018-08-07 03:50
Same root cause with #59

**Comment by sunlin-link** [comment] 2018-08-21 05:51
@BruceDai Please help to verify the fix.

**Comment by Christywl** [comment] 2018-08-22 06:38
Verified it with Chromium nightly build(50746ae), this issue wasn't reproduced with MPS backend, but it can reproduce with BNNS backend. So a new issue #160 was filed for BNNS, close this issue now.

**Closed** 2018-08-22 06:39 UTC
Labels: Mac, bug
