### ISSUE TITLE
[NNAPI] Inception v3/v4(TFLite) quantized models don't work on NNAPI

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#798] opened 2019-05-10 01:06 UTC
**Test Env:**
Chromium Version: nightly build 75.0.3739.0 (3acec85)
Platform: Android(Google Pixel 3) 

**Expected Result:**
Examples should work.

**Actual Result:**
Inception v3/v4(TFLite) quantized models don't work on NNAPI:
<img width="250" alt="inception quantized model-nnapi" src="https://user-images.githubusercontent.com/20039821/57495908-d9a35680-7302-11e9-89d9-3648801a05e0.png">

**How to Reproduce:**
1. Setup test server and start
2. Visit http://localhost:8080/examples/image_classification
3. Select SUSTAINED_SPEED
4. Select one model:

   - Inception v3  quant
   - Inception v4 quant

**Comment by mingmingtasd** [comment] 2019-10-12 08:10
This issue is pending caused by the problem of iteralerLayers tool on Android platform. Please refer to #985.

**Comment by liyananxl** [comment] 2019-11-14 05:41
Re-tested on chromium build M79(e7b9a67), this issue still happened on Google Pixel 3, but it did not happen on Samsung Galaxy Note 10+.

**Comment by mingmingtasd** [comment] 2019-11-14 07:39
> Re-tested on chromium build M79(e7b9a67), this issue still happened on Google Pixel 3, but it did not happen on Samsung Galaxy Note 10+.

Thanks. And it also happened on HUAWEI P20 PRO (Android 9), but it didn't happen on Google Pixel 2XL (Android 10).

**Comment by mingmingtasd** [comment] 2019-11-19 08:51
This issue will be fixed on Android 10. Details are shown below:
![#798issue_android9_huawei](https://user-images.githubusercontent.com/52519066/69128679-ceb65380-0ae7-11ea-928c-44a86f2f378b.png)
According to the log on Huawei P20 PRO (Android 9), the issue is caused by the failure of CONCATENATION OP. For this OP, before API level 29 (Android 10), all input tensors of ANEURALNETWORKS_TENSOR_QUANT8_ASYMM must have the same scale and zeroPoint as the output tensor. There is a function in [1b69cee](https://android.googlesource.com/platform/frameworks/ml/+/1b69ceeb5920503f18b6c6c1233b1fa481b6e634/nn/common/OperationsUtils.cpp#346):

"bool concatenationPrepare(const std::vector<Shape>& inputShapes, int32_t axis, Shape* output)"

This function is used to check:

"nnOpsCheck(inputShapes[i].type == inputShapes[0].type)" 

So the CONCATENATION OP will fail if the equation above is not true.
 
But since API level 29 (Android 10), inputs with different quantization parameters in CONCATENATION are supported by [5776a12](https://android.googlesource.com/platform/frameworks/ml/+/5776a1237634755f862665c9f414254c890bc52b). The "nnOpsCheck(inputShapes[i].type == inputShapes[0].type)" has been deleted in this commit.

**Comment by liyananxl** [comment] 2019-11-20 05:44
Update Google Pixel 3 to Android 10, then re-tested on chromium build M79(e7b9a67), the issue did not happen. So close the issue.

**Closed by liyananxl** 2019-11-20 05:44 UTC
Labels: bug, p2
