### ISSUE TITLE
[MPS] "InvalidStateError: finishfails: 4" happened when running some CTS tests on Mac OS

### ISSUE THREAD

**Issue by BruceDai** [intel/webml-polyfill#58] opened 2018-06-05 10:35 UTC
### Test Env
Chromium Version :  nightly build 65.0.3324.0 (revision 3d99cdd)
Operating System : MacOS

### Expected behavior

Test should be PASS.

### Actual behavior
Error happened as following:
```
  InvalidStateError: finishfails: 4
```

### How to reproduce  
1. Download and install Chromium
2. Launch  Chromium
3. Run test case on Chromium: 
(1) https://brucedai.github.io/nt/test/concatenation.html for concatenation test
(2) https://brucedai.github.io/nt/test/max_pool_2d.html for  max_pool_2d test

**Comment by BruceDai** [comment] 2018-06-05 10:37
We will verify this issue on latest nightly build revision f9e1a31.

**Comment by BruceDai** [comment] 2018-06-06 07:15
Using latest nightly build revision f9e1a31, the same error happened :
```
  InvalidStateError: finishfails: 4
```
when running https://brucedai.github.io/nt/test2/concatenation.html to test concatenation using axis 0, 1, 2 for input tensor as 4-D tensor.

Chromium crashed when running https://brucedai.github.io/nt/test2/concatenation_3.html to test concatenation using axis 3 for input tensor as 4-D tensor, crash details please see the attachment log file.

[concatenation_3.crash.log](https://github.com/intel/webml-polyfill/files/2075089/concatenation_3.crash.log)

**Comment by sunlin-link** [comment] 2018-06-26 04:48
Finding the root cause of Issue 1.
Issue 2 can not be reproduced

**Comment by sunlin-link** [comment] 2018-07-03 06:52
When compiling concatenation, current implementation only supports axis is 3

**Comment by Christywl** [comment] 2018-07-30 06:57
Update the failed tests for this issue:
1. Enable WebML flag, and access to https://brucedai.github.io/nt/test/concatenation.html:
```
check result by Concatenation Test for 4-D input with axis being 0
check result by Concatenation Test for 4-D input with axis being 1
check result by Concatenation Test for 4-D input with axis being 2
```


2. Enable WebML flag, and access to https://brucedai.github.io/nt/testm/cts-all.html
```
check result for Add example
check result for Avg pool float example/4
check result for Depthwise conv2d float   example
check result for Depthwise conv2d float   weights as inputs example
check result for Max pool float example/3
check result for Mul example
check result for Mul relu example
check result for Softmax float example/1
```

**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision 81edd55)
OS : Mac OS
webml-polyfill: commit [4eafead](https://github.com/intel/webml-polyfill/commit/ee18609f980abe735f88e0547a9240c3b2f98ba7)

**Comment by Christywl** [comment] 2018-07-30 07:38
For https://github.com/intel/webml-polyfill/issues/58#issuecomment-394965734:

> Chromium crashed when running https://brucedai.github.io/nt/test/concatenation_3.html to test concatenation using axis 3 for input tensor as 4-D tensor

Filed a new issue to track it: #108

**Comment by fujunwei** [comment] 2019-01-21 08:49
[The implementation of tfjs ](https://github.com/tensorflow/tfjs-core/blob/8c56acfeef847c0943cd890fe506a6dae3bd8bfb/src/kernels/backend_webgl.ts#L623) is reduce n-dimensional to two-dimensional and concat axis 1, finally reshaping  the result to the proper shape, but Maybe the batches can't be reshaped in [MPSNNReshapeNode](https://developer.apple.com/documentation/metalperformanceshaders/mpsnnreshapenode/3037420-initwithsource?language=objc) 
```
- (instancetype)initWithSource:(MPSNNImageNode *)source 
                   resultWidth:(NSUInteger)resultWidth 
                  resultHeight:(NSUInteger)resultHeight 
         resultFeatureChannels:(NSUInteger)resultFeatureChannels;
```
@GreyZzzzzzXh i need your helper to understand the implementation.

**Comment by Christywl** [comment] 2019-07-16 03:08
Split this issue into #892, #893, #894, #895, #896, #897, and close this issue.

**Closed by Christywl** 2019-07-16 03:08 UTC
Labels: Mac, enhancement, p2
