### ISSUE TITLE
[WASM] There is a build error with Emscripten (newest version 1.38.46) tool on WASM

### ISSUE THREAD

**Issue by cuiyanx** [intel/webml-polyfill#1004] opened 2019-09-29 08:20 UTC
There is a build error with Emscripten (newest version 1.38.46) tool on WASM. The [tensorflow](https://github.com/tensorflow/tensorflow/tree/r1.13) version is 1.13.
Error info:
![Screenshot from 2019-09-29 16-16-32](https://user-images.githubusercontent.com/22387607/65829135-842d0d80-e2d4-11e9-9787-3e76371dedd5.png)

**Comment by cuiyanx** [comment] 2019-09-30 03:14
I try to build [nn_ops.js](https://github.com/intel/webml-polyfill/blob/master/src/nn/wasm/nn_ops.js) with [binding.cpp](https://github.com/intel/webml-polyfill/blob/master/src/nn/wasm/src/bind/src/binding.cpp) and Emscripten (newest version 1.38.46) tool and [Tensorflow](https://github.com/tensorflow/tensorflow/tree/r1.15) (branch r1.15), and get 8 errors.

error info:
1.
![Screenshot from 2019-09-30 10-56-53](https://user-images.githubusercontent.com/22387607/65846812-a0cb5300-e371-11e9-8227-2b601abf6f77.png)
2.
![Screenshot from 2019-09-30 10-57-29](https://user-images.githubusercontent.com/22387607/65846821-a4f77080-e371-11e9-8cc6-7bcc2d920949.png)
3.
![Screenshot from 2019-09-30 10-57-59](https://user-images.githubusercontent.com/22387607/65846827-a9bc2480-e371-11e9-92fc-124df204929a.png)
4.
![Screenshot from 2019-09-30 10-58-23](https://user-images.githubusercontent.com/22387607/65846834-afb20580-e371-11e9-9f30-542ab0858476.png)
5.
![Screenshot from 2019-09-30 11-00-10](https://user-images.githubusercontent.com/22387607/65846847-b80a4080-e371-11e9-93a2-db403ceae5f2.png)
6.
![Screenshot from 2019-09-30 11-00-46](https://user-images.githubusercontent.com/22387607/65846853-bb9dc780-e371-11e9-8914-8ff0d83ab75a.png)
7.
![Screenshot from 2019-09-30 11-13-37](https://user-images.githubusercontent.com/22387607/65847278-7084b400-e373-11e9-8650-f025c759ea71.png)
8.
![Screenshot from 2019-09-30 11-13-54](https://user-images.githubusercontent.com/22387607/65847286-74b0d180-e373-11e9-923d-2abaa83b8e67.png)

**Comment by huningxin** [comment] 2019-10-08 06:19
@akineeic , could you please investigate this issue? thanks.

**Comment by Wenzhao-Xiang** [comment] 2019-10-11 05:40
> There is a build error with Emscripten (newest version 1.38.46) tool on WASM. The [tensorflow](https://github.com/tensorflow/tensorflow/tree/r1.13) version is 1.13.
> Error info:

To my understanding, it's the issue of `Runtimeshape` binding, you can change it to 
```c++
class_<RuntimeShape>("RuntimeShape")
    .constructor<int>()
    .function("DimensionsCount", &RuntimeShape::DimensionsCount)
    .function("Dims", &RuntimeShape::Dims)
    .function("SetDim", &RuntimeShape::SetDim)
    ;
```

**Comment by huningxin** [comment] 2019-10-11 05:42
Thanks @Wenzhao-Xiang . @akineeic , could you please follow Wenzhao's suggestion and create a PR?

**Comment by Wenzhao-Xiang** [comment] 2019-10-11 06:00
> I try to build [nn_ops.js](https://github.com/intel/webml-polyfill/blob/master/src/nn/wasm/nn_ops.js) with [binding.cpp](https://github.com/intel/webml-polyfill/blob/master/src/nn/wasm/src/bind/src/binding.cpp) and Emscripten (newest version 1.38.46) tool and [Tensorflow](https://github.com/tensorflow/tensorflow/tree/r1.15) (branch r1.15), and get 8 errors.

In the r1.15 release, `tflite` changed some API definitions, so we need to modify the `binding.cpp` to match them first. The biggest difference is that it uses `CpuBackendContext` to integrate `Eigen`, `Gemmlowp` and its own experimental library `Ruby`, which makes the API more concise to use. I did some work to update the tensorflow version before, but it seems that there are some issue with the toolchain when compiling `CpuBackendContext`. I haven't investegated this issue yet. 
Hope this information can help you if you want to update the tf version.

**Comment by akineeic** [comment] 2019-10-11 06:40
> Thanks @Wenzhao-Xiang . @akineeic , could you please follow Wenzhao's suggestion and create a PR?

Thanks @Wenzhao-Xiang , I have reproduced the error and solved it followed wenzhao's suggestion. It seems caused by the version of Emscripten. I'll make a PR later.

**Comment by akineeic** [comment] 2019-10-12 03:04
This issue has fixed in #1021.
Close the issue.

**Comment by huningxin** [comment] 2019-10-12 04:17
@akineeic , the process is that we close the issue after PR merged. And if you put fix key word in your PR, the issue will be automatically closed after PR merged. Please check out https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by akineeic** [comment] 2019-10-12 04:26
> @akineeic , the process is that we close the issue after PR merged. And if you put fix key word in your PR, the issue will be automatically closed after PR merged. Please check out https://help.github.com/en/articles/closing-issues-using-keywords

Thanks @huningxin, I have modified the pull request description.

**Comment by akineeic** [comment] 2019-10-29 06:29
It seems that the version 1.38.41 or later of emscripten does't support our code of constructor's overload. To overload the constructor of RuntimeShape correctly, I have created an [issue](https://github.com/emscripten-core/emscripten/issues/9704) in emscripten repo. Waiting for their advanced infomation.

**Comment by huningxin** [comment] 2019-10-29 06:36
Thanks @akineeic . Let's see upstream's inputs. As your PR https://github.com/intel/webml-polyfill/pull/1021 works for both 1.38.40 and 1.38.41. It's kind of working.

**Closed** 2019-10-30 02:05 UTC
