### ISSUE TITLE
[webgl2] The returned type of Model methods is not 'void' type

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#73] opened 2018-06-25 06:26 UTC
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Mac OS X 10.13.4

**Expected Result:**
The returned type of Model methods is 'void' type

**Actual Result:**
The returned type of Model methods is not 'void' type, it returns 0

**How to reproduce:**
1.Download and install Chromium
2.Launch Chromium
3. Run test case on Chromium: https://brucedai.github.io/nt/test/index-local.html?backend=webgl2
4. Check the result for this test in **addOperand API**/**setOperandValue API**/**addOperation API**/**identifyInputsAndOutputs API**
for example:
```
    it('check return value is of "void" type', function() {
      return nn.createModel(options).then((model)=>{
        assert.equal(model.addOperand({type: nn.INT32}), undefined);
      });
    });
```

**Comment by BruceDai** [comment] 2018-06-26 07:17
Duplicate of #75, closed it.

**Closed by BruceDai** 2018-06-26 07:17 UTC
